version: '3'
services:
  zookeeper:
    image: alexsuch/kafka:0.11.0.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - MODE=ZOOKEEPER
    ports:
      - "2181:2181"
  kafka:
    image: alexsuch/kafka:0.11.0.0
    container_name: kafka
    hostname: kafka
    environment:
      - MODE=KAFKA
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"