version: '3'
services:
  zookeeper:
    image: alexsuch/kafka:0.11.0.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - MODE=ZOOKEEPER
      - ZOOKEPER_PORT=2181
    ports:
      - "2181:2181"
  zookeeper2:
    image: alexsuch/kafka:0.11.0.0
    container_name: zookeeper2
    hostname: zookeeper2
    environment:
      - MODE=ZOOKEEPER
      - ZOOKEPER_PORT=2182
    ports:
      - "2182:2182"
  kafka1:
    image: alexsuch/kafka:0.11.0.0
    container_name: kafka1
    hostname: kafka1
    environment:
      - MODE=KAFKA
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2182
      - KAFKA_BROKER_ID=0
      - KAFKA_PORT=9092
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
    ports:
      - "9092:9092"
  kafka2:
    image: alexsuch/kafka:0.11.0.0
    container_name: kafka2
    hostname: kafka2
    environment:
      - MODE=KAFKA
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2182
      - KAFKA_BROKER_ID=1
      - KAFKA_PORT=9093
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
    ports:
      - "9093:9093"
  kafka3:
    image: alexsuch/kafka:0.11.0.0
    container_name: kafka3
    hostname: kafka3
    environment:
      - MODE=KAFKA
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2182
      - KAFKA_BROKER_ID=2
      - KAFKA_PORT=9094
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
    ports:
      - "9094:9094"